# Generated by Django 3.0.5 on 2020-07-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone_no', models.BigIntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recep_name', models.CharField(max_length=100)),
                ('recep_id', models.EmailField(max_length=254)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_id', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_appointment_id', models.IntegerField()),
                ('patient_name', models.CharField(default='', max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateField()),
                ('udated_at', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('prescription', models.CharField(blank=True, max_length=2000)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos.doctors')),
                ('patient_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hos.patient')),
            ],
        ),
    ]
